// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArBW-dkpltT0rXhm4JElGwMgsRJGX-4mM',
    appId: '1:560534304880:web:8049886472790bf74ddcb5',
    messagingSenderId: '560534304880',
    projectId: 'chatappyash-70f10',
    authDomain: 'chatappyash-70f10.firebaseapp.com',
    storageBucket: 'chatappyash-70f10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEkKY0so-poDb1eR-FRqg0WIM9E1u4TkE',
    appId: '1:560534304880:android:acd38cb2079927e64ddcb5',
    messagingSenderId: '560534304880',
    projectId: 'chatappyash-70f10',
    storageBucket: 'chatappyash-70f10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMSqeQClPRAUsmPlvh6MFdpE8eLRActv4',
    appId: '1:560534304880:ios:bf6990aa422dcd604ddcb5',
    messagingSenderId: '560534304880',
    projectId: 'chatappyash-70f10',
    storageBucket: 'chatappyash-70f10.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMSqeQClPRAUsmPlvh6MFdpE8eLRActv4',
    appId: '1:560534304880:ios:bf6990aa422dcd604ddcb5',
    messagingSenderId: '560534304880',
    projectId: 'chatappyash-70f10',
    storageBucket: 'chatappyash-70f10.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArBW-dkpltT0rXhm4JElGwMgsRJGX-4mM',
    appId: '1:560534304880:web:29868606f05bfc4e4ddcb5',
    messagingSenderId: '560534304880',
    projectId: 'chatappyash-70f10',
    authDomain: 'chatappyash-70f10.firebaseapp.com',
    storageBucket: 'chatappyash-70f10.appspot.com',
  );

}